name: Test Automation Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Running test automation with Maven
      run: mvn clean test

    - name: Upload test result
      if: always()  # This ensures the report is uploaded even if tests fail
      uses: actions/upload-artifact@v4.6.2
      with:
        name: surefire-reports
        path: target/surefire-reports/
